controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_auth_check:
    path: /api/v1/auth

app.swagger_ui:
    path: /api/v1/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.redocly:
    path: /api/v1/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.redocly }

app.swagger:
    path: /api/v1/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }